modLoader="javafml"
loaderVersion="[43,)"
license="MIT License"

[[mods]]
modId="aae_sharkos"
version="10.23.24"
displayName="AAE Sharkos"
credits="Find the book."
displayURL="https://www.twitch.tv/engiegames"
logoFile="logo.png"
authors="EngieGames"
description="Made with MCreator"

[[dependencies.aae_sharkos]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2]"
    ordering="NONE"
    side="BOTH"




